CSS Format/Minify Tool
developertools-tech/developertools.tech pull request #29
Opened 2022-10-05 22:46 UTC by nosecreek

## Type of Pull Request

- [ ] Bug fix
- [*] Enhancement

Related Issue #s or links (if any): 
#14 

## Description of Changes
Added a CSS page which includes a formatter and minifier.

Note: minification is not currently available for SCSS/LESS. SCSS cannot currently be run in the browser (see https://github.com/sass/dart-sass/issues/25).

2022-10-05 23:12 UTC, dlford requested changes
@nosecreek Great job on this! I just have a couple notes if it's not too much trouble.

2022-10-05 23:12 UTC, dlford commented on __TESTS__/css.spec.tsx
> +
Can we also test that minify works correctly?

2022-10-05 23:12 UTC, dlford commented on __TESTS__/css.spec.tsx
> +    expect(formattedCss.innerHTML).toContain('body {');
I'd rather see us match exact output here, like the JSON tests.

2022-10-06 00:37 UTC, nosecreek commented
I think those are both great suggestions. Should be fixed by the latest commit.

2022-10-06 00:45 UTC, dlford commented
@nosecreek Great, thank you!

2022-10-06 00:45 UTC, merged