Adding docker support
developertools-tech/developertools.tech pull request #59
Opened 2022-10-11 19:18 UTC by aliabbasjaffri

## Type of Pull Request

- [ ] Bug fix
- [x] Enhancement

Related Issue #s or links (if any): 

## Description of Changes

Added support for Docker. You can find the details on this issue: https://github.com/developertools-tech/developertools.tech/issues/42

2022-10-11 20:05 UTC, dlford requested changes
@aliabbasjaffri Maybe I missed something but I thought the dockerizing was for development, looks like we are doing production builds here?

I don't see need for production docker builds, since this is a fully open source PWA, anyone can use it for free online or offline via the website.

2022-10-11 20:05 UTC, dlford commented on README.md
> +## Getting Started
Please don't change the README file.

2022-10-18 07:04 UTC, aliabbasjaffri commented
Indeed! Reverting the changes to have a single click development setup using `docker-compose up`

2022-10-20 07:44 UTC, aliabbasjaffri commented
@dlford the changes are integrated. let me know if there's anything else.

2022-10-26 13:13 UTC, closed without merging